version: 1.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:iam::317225729511:role/ecsTaskExecutionRole/movies-main:16"
        LoadBalancerInfo:
          ContainerName: "movies-main"
          ContainerPort: "8100"
        PlatformVersion: "LATEST"