apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "2"
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"generation":1,"labels":{"app":"moveis-factory"},"name":"moveis-factory","namespace":"default"},"spec":{"replicas":2,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app":"moveis-factory"}},"strategy":{"rollingUpdate":{"maxSurge":"25%","maxUnavailable":"25%"},"type":"RollingUpdate"},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"moveis-factory"}},"spec":{"containers":[{"image":"muradshahin/movies-factory-movies-factory:0.0.2-SNAPSHOT","imagePullPolicy":"IfNotPresent","name":"movies-factory-movies-factory"}]}}}}
    creationTimestamp: "2022-01-19T18:46:10Z"
    generation: 2
    labels:
      app: moveis-factory
    name: moveis-factory
    namespace: default
    resourceVersion: "74020"
    uid: 9d21ac8a-b2a6-4dd2-96c0-b0ef9dfe2242
  spec:
    progressDeadlineSeconds: 600
    replicas: 2
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: moveis-factory
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: moveis-factory
      spec:
        containers:
        - image: muradshahin/movies-factory-movies-factory:0.0.2-SNAPSHOT
          imagePullPolicy: IfNotPresent
          name: movies-factory-movies-factory
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    availableReplicas: 2
    conditions:
    - lastTransitionTime: "2022-01-19T22:00:53Z"
      lastUpdateTime: "2022-01-19T22:00:53Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    - lastTransitionTime: "2022-01-19T18:46:10Z"
      lastUpdateTime: "2022-01-19T22:00:58Z"
      message: ReplicaSet "moveis-factory-698d996596" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    observedGeneration: 2
    readyReplicas: 2
    replicas: 2
    updatedReplicas: 2
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "4"
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"movies-home"},"name":"movies-home","namespace":"default"},"spec":{"replicas":1,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app":"movies-home"}},"strategy":{"rollingUpdate":{"maxSurge":"25%","maxUnavailable":"25%"},"type":"RollingUpdate"},"template":{"metadata":{"labels":{"app":"movies-home"}},"spec":{"containers":[{"env":[{"name":"MOVIES_FACTORY_URL","value":"http://movies-factory"}],"image":"muradshahin/movies-main-movies-main:0.0.2-SNAPSHOT","imagePullPolicy":"IfNotPresent","name":"movies-main-movies-main"}]}}}}
    creationTimestamp: "2022-01-19T21:29:07Z"
    generation: 5
    labels:
      app: movies-home
    name: movies-home
    namespace: default
    resourceVersion: "81421"
    uid: d98e19d2-d970-4b10-96fc-9e679ec821aa
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: movies-home
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: movies-home
      spec:
        containers:
        - env:
          - name: MOVIES_FACTORY_URL
            value: http://movies-factory
          image: muradshahin/movies-main-movies-main:0.0.2-SNAPSHOT
          imagePullPolicy: IfNotPresent
          name: movies-main-movies-main
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    availableReplicas: 1
    conditions:
    - lastTransitionTime: "2022-01-19T21:29:16Z"
      lastUpdateTime: "2022-01-19T21:29:16Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    - lastTransitionTime: "2022-01-19T21:29:07Z"
      lastUpdateTime: "2022-01-19T22:21:00Z"
      message: ReplicaSet "movies-home-76576fbd65" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    observedGeneration: 5
    readyReplicas: 1
    replicas: 1
    updatedReplicas: 1
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
