apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: movies-home
  name: movies-home
  namespace: default
spec:
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: movies-home
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: movies-home
    spec:
      containers:
      - image: muradshahin/movies-main-movies-main:0.0.11-SNAPSHOT
        imagePullPolicy: IfNotPresent
        name: movies-main-movies-main
        readinessProbe:
          httpGet:
            port: 8100
            path: /welcome
        livenessProbe:
          httpGet:
            port: 8100
            path: /welcome  
        # env:
        #   - name: MOVIES_FACTORY_URL
        #     value: http://movies-factory
        # envFrom:
        #   - configMapRef:
        #       name: movies-home
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: movies-home
  name: movies-home
  namespace: default
spec:
  ports:
  - port: 8100
    protocol: TCP
    targetPort: 8100
  selector:
    app: movies-home
  sessionAffinity: None
  type: LoadBalancer

---
apiVersion: v1
data:
  MOVIES_FACTORY_URL: http://movies-factory
kind: ConfigMap
metadata:
  name: movies-home
  namespace: default


